/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testarrays;

import java.util.Arrays;
import org.checkerframework.checker.signedness.qual.Unsigned;
import org.checkerframework.checker.signedness.qual.Signed;

public class AlsoNotApp<N extends Number> {

    public String doToString(N n) {
      return n.toString();
    }


}
