/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testarrays;

import java.util.Arrays;
import org.checkerframework.checker.signedness.qual.Unsigned;
import org.checkerframework.checker.signedness.qual.Signed;

public class App {

    public static void main(String[] args) {
      testCompile(2);
      testCompile(-2);
      testCompile((@Signed int) 2);
    }


    public static void testCompile(@Unsigned int x) {
      @Unsigned int[] arr = {1, 2, 3, 4, 5, 56};
     
      Arrays.fill(arr, x);
      Arrays.fill(arr, (@Unsigned int) Integer.valueOf(-2));
      Arrays.fill(arr, Integer.valueOf(-2));
      Arrays.fill(arr, (@Unsigned int) Integer.valueOf(2));
    }
}
