/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testarrays;

import java.util.Arrays;
import org.checkerframework.checker.signedness.qual.Unsigned;
import org.checkerframework.checker.signedness.qual.Signed;

public class App {

    public static void main(String[] args) {
      NotApp<String> nas = new NotApp<>();
      AlsoNotApp<Integer> anai = new AlsoNotApp<>();
      System.out.println(nas.doToString("hi"));
      System.out.println(anai.doToString(1));
    }


}
