/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testarrays;

import org.checkerframework.checker.signedness.qual.Unsigned;
import org.checkerframework.checker.signedness.qual.Signed;

public class App {

    public static void main(String[] args) {
        @Unsigned int x = 2;
        String s = "foo";
        String t = s+x;
        String u = s+Integer.toUnsignedString(x);
        System.out.println(s);
        System.out.println(t);
        System.out.println(u);
    }


}
